# Site settings
author: Kate Jewett Williams
title: kjdub01.github.io
header-img: img/home-bg.png
email: kjewettwilliams@gmail.com
copyright_name: Kate Jewett Williams
description: > # this means to ignore newlines until "baseurl:"
   
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: kjdub01
github_username:  kjdub01

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
