# Site settings
title: 
header-img: img/home-bg.png
email: kjewettwilliams@gmail.com
copyright_name: kjdub01
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kjdub01
learn_profile: kjdub01
email_username: kjewettwilliams@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
